Run itests in same stage as build/official-image test
To prevent concurrent runs from conflicting:

    docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.50/containers/create?name=crate: Conflict ("Conflict. The container name "/crate" is already in use by container "3f419610d31cb7a7cfbab84fa3e8679606686cfded4397216b0ea6bb8ac4f898". You have to remove (or rename) that container to be able to reuse that name.")